# Generated by Django 6.0.3 on 2026-04-15 01:30

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sig',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('meeting_time', models.CharField(blank=True, max_length=100)),
                ('meeting_day', models.CharField(choices=[('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=11)),
                ('every_x_weeks', models.IntegerField(default=1)),
                ('meeting_location', models.CharField(blank=True, max_length=100)),
                ('discord_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('git_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='sigs/')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='officers/')),
                ('sig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='core.sig')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('discord_url', models.URLField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='events/')),
                ('attachment', models.FileField(blank=True, upload_to='attachments/')),
                ('sig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sig')),
            ],
        ),
    ]
