# Generated by Django 6.0.3 on 2026-04-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='discord_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='registrationLink',
            field=models.URLField(blank=True),
        ),
    ]
