# Generated by Django 6.0.3 on 2026-04-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registrationLink',
            field=models.URLField(blank=True),
        ),
    ]
