# Generated by Django 6.0.3 on 2026-04-22 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sig_every_x_weeks'),
        ('core', '0002_rename_discord_url_event_url_event_contact_and_more'),
    ]

    operations = [
    ]
