# Generated by Django 6.0.3 on 2026-04-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_registrationlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
