# Generated by Django 6.0.3 on 2026-04-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='discord_url',
            new_name='url',
        ),
    ]
