# Generated by Django 6.0.3 on 2026-04-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20260422_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sig',
            name='every_x_weeks',
            field=models.IntegerField(default=1),
        ),
    ]
