# Generated by Django 6.0.3 on 2026-04-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_discord_url_event_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sig',
            old_name='meeting_time',
            new_name='meeting_time_start',
        ),
        migrations.AddField(
            model_name='sig',
            name='meeting_time_end',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
